services:
  postgres:
    image: postgres:17-alpine
    container_name: ec-pj
    environment:
      POSTGRES_USER: ${POSTGRES_USER-:demo}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:-demo}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ec-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-demo}"]
      interval: 10s
      timeout: 5s
      retries: 5
networks:
  ec-network:
    driver: bridge
volumes:
  postgres_data:
    driver: local
