CREATE TABLE users (
	id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
	username VARCHAR(100) UNIQUE NOT NULL,
	phone VARCHAR(30) UNIQUE NOT NULL,
	email VARCHAR(150) UNIQUE NOT NULL,
	password VARCHAR(100) NOT NULL,
	salt VARCHAR(50) NOT NULL,
	first_name VARCHAR(100),
	last_name VARCHAR(100),
	status VARCHAR(10) NOT NULL DEFAULT 'active',
	birthday DATE DEFAULT NULL,
	role VARCHAR(10) NOT NULL DEFAULT 'user',
	gender VARCHAR (10) NOT NULL,
	avatar TEXT DEFAULT NULL,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

